### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by MustakMU** [hsuRush/DeepANPR#1]
Hi Steven,
Thanks for sharing such awesome code..
I'm trying to follow the procedure that you have mentioned but i'm unable to find training dataset. can you please point me where i can dataset?
Thanks

**Comment by hsuRush** [comment]
Training data is under [NDA](https://en.wikipedia.org/wiki/Non-disclosure_agreement), you can label yourself by [labelimg](https://github.com/tzutalin/labelImg).
